export const auth = {
  signin: '登录',
  signup: '注册',
  signout: '登出',
  name: '姓名',
  email: '邮箱',
  phone: '手机号',
  language: '语言',
  timezone: '时区',
  password: '密码',
  password_confirmation: '确认密码',
  password_change: '重置密码',
  privacy_agree: '接受REDTABLE会员条款',
  forgot_password: '找回密码',
  remember_me: '记住账号',
  naver: 'NAVER',
  kakao: 'Kakao',
  facebook: 'Facebook',
  google: 'Google',
  save: '保存',

  reset_password: '重置密码',
  send_reset_link: '发送密码重置链接',
  sns_login_txt: '请使用已有的账号登录！',
  login_email_error: '请确认账号和密码',
  terms: '会员条款',
  signup_terms_agree_alert: '请确认会员条款',
  select_language_txt: '选择语言',
}
