export const cart = {
  cart: '购物车',
  remove_all: '全部删除',
  empty: '暂未有任何购物车</h3>请选择菜单并添加到购物车',
  other_product_add: '+ 追加购买其他商品',
  remove_all_alert: '是否清空您的购物车？',
  // 'payment' : '立即支付',
  payment: '支付',
  order: '立即订购',
  add_1: '添加',
  add_2: '个',
  add_3: '(订购该套餐时，无法与其他商品一并支付)',
  blank_basket: '暂未有任何购物车',
  blank_basket_msg: '请选择菜单并添加到购物车',
}
