/* eslint-disable no-dupe-keys */
export const common = {
  home: '首页',
  language: 'zh-Hans',
  city: '城市',
  place: 'Must Go #',
  'must-eat': 'Must Eat #',
  mypage: '我的主页',
  wish_list: '收藏',
  cart: '购物车',
  order_history: '订单',
  event: '优惠活动',
  promotion: '优惠活动',
  theme: '主题活动',
  all_stores: '全部店铺',
  menu: '菜单',
  close: '关闭',
  close_3day: '3天停看',
  price: '价格',
  privacy: '个人信息保护政策',
  term: '使用条款',
  refund: '退款政策',
  cs: '1:1咨询',
  select: '== 选择 ==',
  footer:
    '咨询热线 02-6964-7959<br>电子邮件 marketing@redtable.kr<br>客服时间 平日 10:00~18:00（周末及法定节假日休业）',
  company_info:
    '(株)REDTABLE 代表 都亥镕<br>营业执照编号：206-86-50534<br>通信销售业申报号码：2019-中区-0501<br>旅游事业者（一般旅游业）登录号码：第2019-000024号<br><br>首尔特别市钟路区清溪川路85首尔观光广场9楼（贯铁洞，三一大厦）',
  not_again: '今天不再显示广告',
  usage: '订购及使用方法',
  more: '更多',
  no_wishlist: '没有宝贝',
  no_orderlist: 'Nothing ordered yet.',
  food: '必吃',
  srch_txt: '搜索地区/商品',
  filter: '筛选',
  sort: '排序',
  srch_tit: '搜索',
  srch_sub_tit: '请输入关键词',
  srch_history: '搜索记录',
  srch_del_keyword: '全部删除',
  srch_most_popular: '热搜',
  main_buynow_ico_txt: 'Pay & Reservation',
  main_reservation_ico_txt: 'Reservation Only',
  promotion: '优惠活动',
  theme: '主题活动',
  stores: '店铺',
  products: '商品',
  point_history: 'Point usage history',
  coupon_register: 'Regist point coupon',
  one_of_those_days: '今天吃什么？',
  fine_time_to_dine: '至尊奢华，照片永存',
  there_is_no_travel_without_food: '旅行就是要吃！吃！吃！',
  buy_now_eat_now: '现购、现吃！',
  the_local_favorite_restaurants: '小众巷子，地道美食！',
  top_hot_places_in_korea: '韩国人气美食店铺榜',
  ready_to_bang_for_the_buck: '超实惠推荐',
  deals: '优惠',
  discount: '打折',
}
